# Generated by Django 4.2.3 on 2023-07-31 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projectdjango_delete_projetecdjango'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 15, 10, 3, 205082), verbose_name='Posting date')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectDjango',
        ),
    ]
