# Generated by Django 4.2.3 on 2023-07-31 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_my_movies_delete_projectdjango'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_movies',
            name='movie_cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='my_movies',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 15, 27, 9, 688217), verbose_name='Posting date'),
        ),
    ]
