# Generated by Django 4.2.3 on 2023-07-31 18:32

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_my_movies_movie_cover_url_alter_my_movies_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_movies',
            name='movie_cover_url',
        ),
        migrations.AddField(
            model_name='my_movies',
            name='movie_cover',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
        migrations.AlterField(
            model_name='my_movies',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 15, 32, 10, 535690), verbose_name='Posting date'),
        ),
    ]
