# Generated by Django 4.2.3 on 2023-07-31 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_my_movies_movie_cover_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_movies',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 15, 53, 9, 231708), verbose_name='Posting date'),
        ),
    ]
