# Generated by Django 4.2.3 on 2023-07-31 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_my_movies_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_movies',
            name='data',
        ),
        migrations.AddField(
            model_name='my_movies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 16, 5, 16, 572635), verbose_name='Posting date'),
        ),
    ]
