# Generated by Django 4.2.3 on 2023-07-31 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_my_movies_data_my_movies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_movies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 17, 23, 54, 26785), verbose_name='Posting date'),
        ),
    ]
