# Generated by Django 4.2.3 on 2023-07-31 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_my_movies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_movies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 18, 12, 41, 536731), verbose_name='Posting date'),
        ),
        migrations.AlterField(
            model_name='my_movies',
            name='year',
            field=models.DateField(),
        ),
    ]
