# Generated by Django 4.2.3 on 2023-08-01 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_my_movies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_movies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 19, 29, 8, 453453), verbose_name='Posting date'),
        ),
    ]
