# Generated by Django 4.2.3 on 2023-08-01 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_my_movies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_movies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 20, 12, 3, 760557), verbose_name='Posting date'),
        ),
    ]
